apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: db-cluster-1
  region: us-east-1
managedNodeGroups:
  - name: employee-node-group
    instanceType: m5.large
    desiredCapacity: 1
    amiFamily: Bottlerocket     
    privateNetworking: true
    taints:
      - key: "node.cilium.io/agent-not-ready"
        value: "true"
        effect: "NoExecute"